services:
   tftp_server:
      image: danrue/tftpd-hpa
      ports:
         - "69:69/udp"
      volumes:
         - type: bind
           source: .
           target: /srv/tftp
           read_only: true
      restart: unless-stopped
