services:
   tftp_server:
      image: danrue/tftpd-hpa
      ports:
         - "${publish_ports:-69}:69/udp"
      volumes:
         - type: bind
           source: ${publish_directory:-.}
           target: /srv/tftp
           read_only: ${publish_directory_ro:-true}
      restart: unless-stopped
